---
name: Homegear
version: 0.8.22022102-3497
slug: homegear
image: kovaljan/homegear
description: Homegear nightly as Hassio add-on
startup: services
webui: "http://[HOST]:[PORT:2001]/admin"
boot: auto
init: false
hassio_api: true
hassio_role: default
ports:
  2001/tcp: 2001
  2002/tcp: null
  2003/tcp: null
  80/tcp: null
  443/tcp: null
ports_description:
  2001/tcp: HomeGear RPC/WEB port
timeout: 60
arch:
  - amd64
map:
  - config:rw
  - share:rw
  - ssl
environment:
  PUID: "1000"
  PGID: "1000"
  S6_SERVICES_GRACETIME: "50000"
  TZ: Europe/Bratislava
services:
  - mqtt:need
options:
schema:
watchdog: "http://[HOST]:[PORT:2001]/admin"
